import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex flex-col items-center justify-center min-h-screen  text-foreground font-geist-sans antialiased"
      >
        <div className="w-full max-w-screen-2xl flex flex-col mx-auto items-center justify-center gap-4 ">
        {children}

        </div>
        <footer className=" w-full ">
          <div className=" w-full max-w-screen-lg flex flex-col mx-auto items-center justify-center gap-4 border-t-2 border-foreground p-4">  
          <small>Desenvolvido por Luis Soares</small>
          </div>
        </footer>
      </body>
    </html>
  );
}
