import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex flex-col items-center justify-center min-h-screen  text-foreground font-geist-sans"
      >
        <div className="w-full max-w-[1400px] bg-black flex flex-col mx-auto items-center justify-center gap-4 p-4">
        {children}

        </div>
        <footer className=" w-full ">
          <div className=" w-full max-w-screen-lg flex flex-col mx-auto items-center justify-center gap-4 border-t-2 border-foreground p-4">  
          <small>Desenvolvido por Luis Soares</small>
          </div>
        </footer>
      </body>
    </html>
  );
}
